#
# Copyright (C) 2018 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Include the common OEM chipset BoardConfig.
-include device/oneplus/sm8250-common/BoardConfigCommon.mk

DEVICE_PATH := device/oneplus/kebab

# Als correction
SOONG_CONFIG_OPLUS_SENSORS_ALS_POS_L := 680
SOONG_CONFIG_OPLUS_SENSORS_ALS_POS_T := 0
SOONG_CONFIG_OPLUS_SENSORS_ALS_POS_R := 780
SOONG_CONFIG_OPLUS_SENSORS_ALS_POS_B := 50
SOONG_CONFIG_OPLUS_SENSORS_ALS_SCREEN_WIDTH := 1080
SOONG_CONFIG_OPLUS_SENSORS_ALS_SCREEN_HEIGHT := 2400

# Display
TARGET_SCREEN_DENSITY := 450

# HIDL
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml

# Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Partitions
BOARD_ONEPLUS_DYNAMIC_PARTITIONS_SIZE := 7511998464
BOARD_SUPER_PARTITION_SIZE := 7516192768

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/init/fstab.qcom
TARGET_RECOVERY_UI_MARGIN_HEIGHT := 103

# Sensors
SOONG_CONFIG_NAMESPACES += OPLUS_SENSORS
SOONG_CONFIG_OPLUS_SENSORS := \
    ALS_POS_L \
    ALS_POS_T \
    ALS_POS_R \
    ALS_POS_B \
    ALS_SCREEN_WIDTH \
    ALS_SCREEN_HEIGHT

# Touch
SOONG_CONFIG_NAMESPACES += OPLUS_LINEAGE_TOUCH_HAL
SOONG_CONFIG_OPLUS_LINEAGE_TOUCH_HAL := INCLUDE_DIR
SOONG_CONFIG_OPLUS_LINEAGE_TOUCH_HAL_INCLUDE_DIR := $(DEVICE_PATH)/touch/include

# Include the proprietary files BoardConfig.
-include vendor/oneplus/kebab/BoardConfigVendor.mk
